# Generated by Django 4.1.3 on 2022-11-26 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(default='', max_length=20)),
                ('image_url', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(default='', max_length=20)),
                ('image_url', models.CharField(default='NULL', max_length=100)),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=140)),
                ('answer', models.CharField(max_length=280)),
                ('picture_url', models.CharField(default='NULL', max_length=100, null=True)),
                ('counter', models.PositiveSmallIntegerField(default=0)),
                ('last_show', models.DateField(auto_now=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.group')),
                ('stack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.stack')),
            ],
        ),
    ]
